production:
  deny_delete: true
  auto_create: force
  max_repos: 0
  allow_add_local: true
  post_create: /var/lib/redmine/scm-post-create.sh
  svn:
    path: /var/lib/svn
    svnadmin: /usr/bin/svnadmin
    url: svn
  git:
    path: /var/lib/git
    git: /usr/bin/git
    options: --bare
    url: git

development:
